# Generated by Django 2.0 on 2020-07-01 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packmove', '0002_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=200)),
                ('relocationdate', models.CharField(max_length=200)),
                ('fromaddress', models.CharField(max_length=200)),
                ('toaddress', models.CharField(max_length=200)),
                ('requirements', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'quote',
            },
        ),
    ]
